#!/bin/bash
#
# Script to run lint and type checks on Travis-CI.
#
# This file is generated by l2tdevtools update-dependencies.py, any dependency
# related changes should be made in dependencies.ini.

EXIT_SUCCESS=0;
EXIT_FAILURE=1;

RESULT=$${EXIT_SUCCESS};

pylint --version

# Ignore setup.py for now due to:
# setup.py:15:0: E0001: Cannot import 'distutils.command.bdist_msi' due to
# syntax error 'expected an indented block (<unknown>, line 347)' (syntax-error)

for FILE in $$(find ${paths_to_lint} -name \*.py);
do
	echo "Checking: $${FILE}";

	pylint --rcfile=.pylintrc $${FILE};

	if test $$? -ne $${EXIT_SUCCESS};
	then
		RESULT=$${EXIT_FAILURE};
	fi
done

mypy --version

mypy --strict ${project_name};

if test $$? -ne $${EXIT_SUCCESS};
then
	RESULT=$${EXIT_FAILURE};
fi

exit $${RESULT};
